import 'models/recipe.dart';

const RECIPES = const [
  //EGG MASALA
  const Recipe(
    recipeName: 'Egg Masala',
    imageUrl: 'assets/images/egg_curry.png',
    prepTime: 45,
    complexity: Complexity.Simple,
    affordability: Affordability.$$,
    ingredients: [
      ' 4 pcs Boiled Eggs',
      ' 4 tsp Roasted Peanuts',
      ' 2 tsp Sesame seeds',
      ' 1 cup Coconut (Grated)',
      ' 1 tsp Cumin seeds',
      ' 1/2 tsp Fenugreek seeds',
      ' 2 pcs Dry Red chillies',
      ' 4 cloves Garlic (chopped)',
      ' 4 pcs Curry leaves',
      ' 2 pcs Green chillies',
      ' 1 tsp Coriander Powder',
      ' 1 tsp Turmeric powder',
      ' 1 tsp Garam Masala',
      ' 2 tsp Turmeric paste',
      ' to taste Salt',
      ' 2 tsp Oil',
      ' 1 cup water'
    ],
    steps: [
      'Heat one tablespoon of oil in a pan and fry the boiled eggs for 2 minutes. Remove from pan and keep it aside.',
      'Grind the peanuts, sesame seeds, coconut with a little water into a fine paste and keep it aside.',
      'Heat oil in a pan. Add cumin seeds, fenugreek seeds, curry leaves, dry red chillies, garlic and green chillies one by one. Fry for a minute.',
      'Now add the prepared paste of coconut, peanuts and sesame. Fry for 5 minutes on medium flame.',
      'Add turmeric powder, cumin powder, coriander powder, salt and saute for 3-4 minutes.',
      'Add water and mix well. Then add the eggs and tamarind paste. Lastly add garam masala powder and mix well.',
      'Serve hot with steamed rice and a bowl of raita.',
    ],
  ),

  //BANANA CHOCOLATE CAKE
  const Recipe(
    recipeName: 'Banana Chocolate Cake',
    imageUrl: 'assets/images/banana_chocolate_cake.png',
    prepTime: 90,
    complexity: Complexity.Simple,
    affordability: Affordability.$$,
    ingredients: [
      '4 Bananas',
      '1/2 cup Cocoa Powder',
      '1/2 cup Peanut butter ',
    ],
    steps: [
      'First take a bowl and add bananas, peanut butter and cocoa powder in it. Mix this well.',
      'Then take a baking mould, oil it and pour the prepared batter.',
      'Put it in the oven on 200 degree Celsius and bake till it is cooked from inside. Once it is done, let it rest for till room temperature.',
      'Now, in a separate bowl melt some chocolate and then pour it over the cake and refrigerate.',
    ],
  ),

  //PANEER TIKKA TOAST
  const Recipe(
    recipeName: 'Paneer Tikka Toast',
    imageUrl: 'assets/images/paneer_tikka.png',
    prepTime: 45,
    complexity: Complexity.Simple,
    affordability: Affordability.$$,
    ingredients: [
      '1/2 Cup Paneer',
      '3 tbsp Thick curd',
      '2 tbsp Besan',
      '1/2 tbsp Chilli powder',
      '1/2 tbsp Pepper',
      'A pinch of turmeric',
      'Salt according to taste',
      '1/2 cup Roughly chopped onion and capsicum',
      '2 slices Bread',
    ],
    steps: [
      'In a large bowl mix curd, besan, and all the spices. Combine these and then add paneer, onion and capsicum. Keep it aside for 10 minutes.',
      'Heat some oil in a pan and then add the marinated paneer. Let it cook till golden brown.',
      'Then on bread add the paneer tikka and grill the bread.',
      'Serve with mint chutney and tomato ketchup',
    ],
  ),

  //BUTTER GARLIC MUSHROOMS
  const Recipe(
    recipeName: 'Butter Garlic Mushrooms',
    imageUrl: 'assets/images/butter_mushrooms.png',
    prepTime: 45,
    complexity: Complexity.Simple,
    affordability: Affordability.$$,
    ingredients: [
      '2 cup mushrooms',
      '1 tbsp Garlic',
      '1 tbsp Oregano',
      '2 tbsp Butter',
      'Salt to taste',
      'Black Pepper to taste',
    ],
    steps: [
      'Wash the mushrooms under running water and boil them in water till they are soft.',
      'Take a pan and add butter and garlic. Let the flavour of garlic get infused in butter.',
      'Then add the mushrooms and throw in salt, pepper and oregano.',
      'Cook it on a medium flame for 10 minutes.',
    ],
  ),

  //RABRI
  const Recipe(
    recipeName: 'Rabri',
    imageUrl: 'assets/images/rabri.png',
    prepTime: 55,
    complexity: Complexity.Simple,
    affordability: Affordability.$$,
    ingredients: [
      '5 Cups milk, full cream',
      '1/2 cup sugar',
      '4-5 green cardamoms',
      '12-15 almonds (shredded), blanched',
      '2 tbsp pistachios (shredded), blanched',
      'vark leaves (silver leaves) to decorate',
    ],
    steps: [
      'Boil the milk in a wide, heavy-based pan.',
      'Add the sugar and cardamom and simmer over low heat.',
      'Do not stir too often, as a layer of cream should form over it.',
      'After the layer is formed, push it away from the sides towards the centre, stir the milk below it gently to avoid scorching.',
      'Repeat the process till one-third of the volume of milk is left.',
      'The time taken will depend on the richness of the milk and the vessel.',
      'The wider the vessel and the richer the milk, the faster it will thicken.',
      'When done, the colour changes to a beige-cream, and the cream that was pushed aside, collects in layers.',
      'Remove from heat. When cool, transfer to a serving dish.',
      'Garnish with vark leaves(silver leaves) and nuts. Chill and serve.',
    ],
  ),

//CHICKEN MAYO SANDWICH
  const Recipe(
    recipeName: 'Chicken Mayo Sandwich',
    imageUrl: 'assets/images/sandwich.png',
    prepTime: 25,
    complexity: Complexity.Simple,
    affordability: Affordability.$,
    ingredients: [
      '4 Slices Bread',
      '200 gms Chicken Breast',
      '1 tsp Ginger garlic paste',
      'to taste Pepper powder',
      '4-5 Leaves Lettuce',
      '1 tbsp Butter',
      'Salt to taste',
      '1/2 cup Mayonnaise',
    ],
    steps: [
      'Take a container, add chicken pieces, ginger garlic paste, salt and pepper. Mix everything well.',
      'Then take a slice of bread and put it on the worktop. Now, put generous amount of chicken and mayo mixture and spready evenly.',
      'Take another bread slice and cover the mixture with it.',
      'Remove the edges and cut the sandwich into triangular shape.',
      'Serve with some finger chips and enjoy!',
    ],
  ),

//GREEK SALAD
  const Recipe(
    recipeName: 'Greek Salad',
    imageUrl: 'assets/images/greek_salad.png',
    prepTime: 25,
    complexity: Complexity.Simple,
    affordability: Affordability.$,
    ingredients: [
      '1 medium cucumber, peeled and cut into triangles',
      '2 medium tomatoes, cut into triangles',
      '2 medium onions, cut into quarters and layers separated',
      '1 small green capsicum, cut into triangles',
      '1 small yellow bell pepper, cut into triangles',
      '1 small red bell pepper, cut into triangles',
      '6-8 black olives, seeded',
      '20 gm feta cheese, cut into cubes',
      '5-6 lollo rosso lettuce, torn',
      'For the dressing:',
      '2 Tbsp lemon juice',
      '1 tsp chopped fresh oregano',
      '1/2 Tbsp white wine vinegar',
      '1 tsp chopped garlic',
      'Salt to taste',
      '1 tsp black pepper powder',
      '1 Tbsp olive oil',
      '2 Tbsp chopped fresh parsley',
    ],
    steps: [
      'Combine lemon juice, oregano, vinegar, garlic, salt, pepper powder, olive oil and parsley in a bowl and mix well.',
      'Mix together cucumber, tomatoes, onions, capsicum, yellow and red bell pepper and olives in a bowl and toss well.',
      'Pour the dressing on top, add lettuce and toss well.',
      'Add feta cheese and mix gently.',
      'Serve chilled.',
    ],
  ),

//VEG BIRYANI
  const Recipe(
    recipeName: 'Veg Biryani',
    imageUrl: 'assets/images/biryani.png',
    prepTime: 60,
    complexity: Complexity.Challenging,
    affordability: Affordability.$,
    ingredients: [
      '3 tbsp ghee / clarified butter',
      '2 bay leaf / tej patta',
      '2 inch cinnamon stick / dalchini',
      '1 star anise',
      '5 cloves / lavang',
      '4 cardamom / elachi',
      '½ tsp pepper',
      '½ tsp cumin seeds / jeera',
      '1 medium onion (finely chopped)',
      '1 tsp ginger - garlic paste',
      '5 beans (chopped)',
      '10 florets gobi / cauliflower',
      '¼ cup peas / mattar',
      '1 carrot (chopped)',
      '1 potato (cubed)',
      '3 mushrooms (sliced)',
      '1 cup curd / yogurt',
      '½ tsp turmeric / haldi',
      '1 tsp kashmiri chilli powder / lal mirch powder',
      '¼ tsp cumin powder / jeera powder',
      '2 tsp biryani masala',
      'salt to taste',
      '6 tbsp coriander leaves (finely chopped)',
      '20 mint / pudina leaves (roughly chopped)',
      '6 tbsp onions (fried)',
      '1½ cups basmati rice (soaked 30 minutes)',
      '2 tbsp saffron water',
      '2 cups water',
    ],
    steps: [
      'firstly, in a large cooker heat ghee and saute spices.',
      'further, saute onions and ginger - garlic paste well.',
      'additionally, add in mixed vegetables and saute till all vegetables shrinks.',
      'now add in curd keeping flame on low.',
      'also add in spice powder and salt to taste. mix well.',
      'also add in coriander leaves, mint leaves and fried onions.',
      'spread soaked basmati rice.',
      'further sprinkle biryani masala powder and salt.',
      'also place in coriander leaves, mint and fried onions.',
      'additionally, pour in saffron water and ghee.',
      'pour water and simmer for 25 minutes.',
      'finally, serve veg biryani prepared in cooker along with raita.',
    ],
  ),
];
